# Generated by Django 5.1.2 on 2024-10-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('base1.html', 'Base Template 1'), ('base2.html', 'Base Template 2')], default='base1.html', max_length=100)),
            ],
        ),
    ]
