# Generated by Django 5.1.2 on 2024-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='template',
            field=models.CharField(choices=[('base1.html', 'navbar 1'), ('base2.html', 'navbar 2'), ('base3.html', 'navbar 3')], default='base1.html', max_length=100),
        ),
    ]
