# Generated by Django 5.1.2 on 2024-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_sitesettings_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='current_template',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='description',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='template',
            field=models.CharField(choices=[('base1.html', 'navbar 1'), ('base2.html', 'navbar 2'), ('base3.html', 'navbar 3')], default='base1.html', max_length=100),
        ),
    ]
